### ISSUE TITLE
CSS within <style> elements is not highlighted.

### ISSUE THREAD

**Issue by alanwj** [jonsmithers/vim-html-template-literals#20]
Example template string:

    const s = html`<style>p { font-weight: bold; }</style>`;

The content of the style tag does not get highlighted as CSS.

Using a separate `css` tagged template is a workaround, but it would be a nice feature if this worked within an html template string.

**Comment by jonsmithers** [comment]
I think https://github.com/jonsmithers/vim-html-template-literals/commit/e6f3f8ffaae9c2f9deea2bbb596b64468041616c fixed this issue as well. Thanks for reporting!

**Comment by alanwj** [comment]
Both CSS highlighting issues I reported appear fixed.  Thanks for the quick fix!
