### ISSUE TITLE
Request for htmlStartTag

### ISSUE THREAD

**Issue by dman777** [jonsmithers/vim-html-template-literals#8]
Hello,

for syntax object parsing in the html, there is a `htmlEndtag` but not a `htmlStartTag`. This is a request for a `htmlStartTag`, please. This will allow theming `<>` `</>` to match. 

Thanks! 
-Darin

**Comment by jonsmithers** [comment]
Hey!

`htmlStartTag` does appear to be absent, however I _do_ see a `htmlTag`. I think that's what you want?

These syntax groups are defined in [`$VIMRUNTIME/syntax/html.vim`](https://github.com/vim/vim/blob/master/runtime/syntax/html.vim) (which is outside the domain of this plugin). If it's helpful, I use this [vimtip](http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor) a lot to identify the current syntax group under the cursor.
